language: ruby
rvm:
  - 2.0.0
  - 1.9.3
branches:
  only:
    - master
    - develop
env:
  - REDMINE_VERSION=2.5.1 VERBOSE=yes
  - REDMINE_VERSION=2.6.2 VERBOSE=yes
script:
  - export PLUGIN=code_audit
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./tools/travis/init.sh -r || exit 1
  - bash -x ./tools/travis/init.sh -i || exit 1
  - bash -x ./tools/travis/init.sh -t || exit 1
  - bash -x ./tools/travis/init.sh -u || exit 1